<a href="https://colab.research.google.com/github/Subham0075/Data_Analysis_Datasets/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
tita = pd.read_csv('/content/titanic.zip')
tita

,Unnamed: 0,Pclass,SibSp,Parch,Sex_female,Sex_male,Age_Children,Age_Teenage,Age_Adult,Age_Elder,Embarked_C,Embarked_Q,Embarked_S,Fare_Low_fare,Fare_median_fare,Fare_Average_fare,Fare_high_fare
0,0,3,1,0,0,1,0,0,1,0,0,0,1,1,0,0,0
1,1,1,1,0,1,0,0,0,1,0,1,0,0,0,0,0,1
2,2,3,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0
3,3,1,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1
4,4,3,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,2,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0
887,887,1,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0
888,888,3,1,2,1,0,0,0,1,0,0,0,1,0,0,1,0
889,889,1,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0
890,890,3,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0

In [ ]:
tita.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         891 non-null    int64
 1   Pclass             891 non-null    int64
 2   SibSp              891 non-null    int64
 3   Parch              891 non-null    int64
 4   Sex_female         891 non-null    int64
 5   Sex_male           891 non-null    int64
 6   Age_Children       891 non-null    int64
 7   Age_Teenage        891 non-null    int64
 8   Age_Adult          891 non-null    int64
 9   Age_Elder          891 non-null    int64
 10  Embarked_C         891 non-null    int64
 11  Embarked_Q         891 non-null    int64
 12  Embarked_S         891 non-null    int64
 13  Fare_Low_fare      891 non-null    int64
 14  Fare_median_fare   891 non-null    int64
 15  Fare_Average_fare  891 non-null    int64
 16  Fare_high_fare     891 non-null    int64
dtypes: int64(17)
memory usage: 118.5 KB

In [ ]:
tita[2:30:5]

,Unnamed: 0,Pclass,SibSp,Parch,Sex_female,Sex_male,Age_Children,Age_Teenage,Age_Adult,Age_Elder,Embarked_C,Embarked_Q,Embarked_S,Fare_Low_fare,Fare_median_fare,Fare_Average_fare,Fare_high_fare
2,2,3,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0
7,7,3,3,1,0,1,1,0,0,0,0,0,1,0,0,1,0
12,12,3,0,0,0,1,0,1,0,0,0,0,1,0,1,0,0
17,17,2,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0
22,22,3,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0
27,27,1,3,2,0,1,0,1,0,0,0,0,1,0,0,0,0

In [ ]:
tita.Pclass[0:10:]

0    3
1    1
2    3
3    1
4    3
5    3
6    1
7    3
8    3
9    2
Name: Pclass, dtype: int64

In [ ]:
tita.head()

,Unnamed: 0,Pclass,SibSp,Parch,Sex_female,Sex_male,Age_Children,Age_Teenage,Age_Adult,Age_Elder,Embarked_C,Embarked_Q,Embarked_S,Fare_Low_fare,Fare_median_fare,Fare_Average_fare,Fare_high_fare
0,0,3,1,0,0,1,0,0,1,0,0,0,1,1,0,0,0
1,1,1,1,0,1,0,0,0,1,0,1,0,0,0,0,0,1
2,2,3,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0
3,3,1,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1
4,4,3,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0

In [ ]:
tita.tail()

,Unnamed: 0,Pclass,SibSp,Parch,Sex_female,Sex_male,Age_Children,Age_Teenage,Age_Adult,Age_Elder,Embarked_C,Embarked_Q,Embarked_S,Fare_Low_fare,Fare_median_fare,Fare_Average_fare,Fare_high_fare
886,886,2,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0
887,887,1,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0
888,888,3,1,2,1,0,0,0,1,0,0,0,1,0,0,1,0
889,889,1,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0
890,890,3,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0

In [ ]:
tita=tita.rename(columns={'Pclass':'pclass'})

In [ ]:
tita

,Unnamed: 0,pclass,SibSp,Parch,Sex_female,Sex_male,Age_Children,Age_Teenage,Age_Adult,Age_Elder,Embarked_C,Embarked_Q,Embarked_S,Fare_Low_fare,Fare_median_fare,Fare_Average_fare,Fare_high_fare
0,0,3,1,0,0,1,0,0,1,0,0,0,1,1,0,0,0
1,1,1,1,0,1,0,0,0,1,0,1,0,0,0,0,0,1
2,2,3,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0
3,3,1,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1
4,4,3,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,2,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0
887,887,1,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0
888,888,3,1,2,1,0,0,0,1,0,0,0,1,0,0,1,0
889,889,1,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0
890,890,3,0,0,0,1,0,0,1,0,0,1,0,1,0,0,0

In [ ]:
tita.pclass[0:10:]

0    3
1    1
2    3
3    1
4    3
5    3
6    1
7    3
8    3
9    2
Name: pclass, dtype: int64

In [ ]:
tita.set_index('Unnamed:',inplace=True)

KeyError: "None of ['Unnamed:'] are in the columns"

In [ ]:
tita.dtypes

Unnamed: 0           int64
pclass               int64
SibSp                int64
Parch                int64
Sex_female           int64
Sex_male             int64
Age_Children         int64
Age_Teenage          int64
Age_Adult            int64
Age_Elder            int64
Embarked_C           int64
Embarked_Q           int64
Embarked_S           int64
Fare_Low_fare        int64
Fare_median_fare     int64
Fare_Average_fare    int64
Fare_high_fare       int64
dtype: object

In [ ]:
tita.isnull().sum()

Unnamed: 0           0
pclass               0
SibSp                0
Parch                0
Sex_female           0
Sex_male             0
Age_Children         0
Age_Teenage          0
Age_Adult            0
Age_Elder            0
Embarked_C           0
Embarked_Q           0
Embarked_S           0
Fare_Low_fare        0
Fare_median_fare     0
Fare_Average_fare    0
Fare_high_fare       0
dtype: int64

In [ ]:
tita.describe(include='0')

TypeError: data type '' not understood

In [ ]:
tita.pclass.unique()

array([3, 1, 2])